-- Economy & Shop
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gems INTEGER DEFAULT 500;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS streak_freeze INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS heart_refill INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS wager_active BOOLEAN DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS wager_start_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS xp_boost_end_time TIMESTAMP WITH TIME ZONE;
